export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
};
// token: BQBjGdCa3mXT48VAihYZ_Hy3ZTcGUkCLXFiuR78ZeBZ-MtzhsE_dawq-E8ANePzi0AFPFlJlauwIij5OcCwyBzKhlkkVec-Z224bqDt4qsHaWI08TcXIkj3vSMg4d9elN4f8TAia7Vp1RiFsP0VhJaCGwZ_j_aUiatVcZyP0mu9hvOmbERsA87_WICnrqIDN5Qx5JZHpyF0